volumes:
  project_postgres_data:

networks:
  project_net:
    external: true
  
services:
  project_db:
    image: postgis/postgis:18-3.6
    container_name: project_db_container
    env_file: .env
    volumes:
      - project_postgres_data:/var/lib/postgresql
    networks:
      project_net:

  app:
    build: .
    image: app-image
    container_name: app_container
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - project_db
    networks:
      project_net:
        
    command: sh -c "uv run manage.py migrate && uv run manage.py runserver 0.0.0.0:8000"

